### ISSUE TITLE
작성한 회고 생성 후, 마감일이 지정되지 않는 회고를 수정하게 되면 서버 에러가 발생합니다.

### ISSUE THREAD

**Issue by klmhyeonwoo** [depromeet/layer-server#249]
안녕하세요~ 지인들과 회고 모임을 만들고 회고를 진행하던 도중 버그를 발견하게 되어 리포트 드립니다!
프론트엔드쪽도 작업 내용이 필요하다면 멘션 부탁드립니다!

## 📜 Bug Description
마감일을 지정하지 않고 회고를 생성한 후, 회고를 수정하게 되면 서버 에러가 발생합니다.

## 🐞 Bug Condition
Step01. 마감일을 지정하지 않고 회고 생성
Step02. 회고 수정 버튼을 통해 회고 수정 화면 진입
Step03. 마감일이 지정되지 않는 상태이기 때문에, 그대로 둔 상태로 제목 및 내용 수정 후 저장

## 📷 Bug Screenshot
<img width="480" alt="스크린샷 2024-09-22 오후 10 00 39" src="https://github.com/user-attachments/assets/dd631adb-5fed-441b-a3bb-3347caa1937d">

**Comment by klmhyeonwoo** [comment]
해당 이슈도 예정 기간 산출해주시면 감사드립니다!

**Comment by mikekks** [comment]
넵 목요일에 말씀드리겠습니다!
