### ISSUE TITLE
회고 마감일이 지난 회고여도, 계속 진행 중으로 뜨는 현상이 발생합니다.

### ISSUE THREAD

**Issue by klmhyeonwoo** [depromeet/layer-server#251]
## 📜 Bug Description
회고 마감일이 지난 회고여도, 자동 마감으로 뜨는 것이 아닌 계속 진행 중으로 발생이 됩니다.

## 🐞 Bug Condition
회고 마감일 설정 후, 회고 시간이 지난 경우

## 📷 Bug Screenshot
회고 시작 전의 상태는 `NOT_STARTED` 입니다.
회고 일이 지난 경우에도 상태 값이 변경되어야할 것 같은데, 해당 상태가 그대로다보니 프론트엔드 쪽 로직에서 고려가 되고 있지 않습니다.

**Comment by mikekks** [comment]
감사합니다 !!!!

**Comment by klmhyeonwoo** [comment]
예정 기간 산출해주시면 감사드립니다!

**Comment by mikekks** [comment]
목요일 공유드리겠습니다!
